In [ ]:
Тема “Вычисления с помощью Numpy”

TASK 1

In [ ]:
import numpy as np

In [4]:
a = np.array( [[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])

In [5]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [8]:
a = a.T

In [9]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
mean_a = np.mean(a, axis = 0)

In [14]:
mean_a

array([2. , 8.4])

TASK 2

In [18]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

TASK 3

In [19]:
a_centered_T = a_centered.T
a_centered_T

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [20]:
a_centered_T_1 = [-1. ,  0. ,  1. ,  1. , -1. ]
a_centered_T_2 = [-2.4, -0.4,  2.6,  1.6, -1.4]
a_centered_sp = np.dot(a_centered_T_1, a_centered_T_2 )


In [21]:
a_centered_sp

8.0

In [22]:
N = 5
a_centered_sp / (N-1)

2.0

TASK 4

In [23]:
a_cov = np.cov(a.T)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

Answer: 2.